ansible-navigator:
  # This section defines what happens when, for example, ":open" is used, and
  # any other time we need to open an editor window.
  #
  # * "command" is a string which used to open the editor process. You can use
  #   {filename} or {line_number} anywhere in your command. If set to ~ or
  #   null, the environment variable $EDITOR will be used instead.
  #
  # * "console" is a boolean. If the editor runs in a terminal, set this to
  #   true so that curses will suspend until the editor quits. Otherwise, set
  #   it to false.
  editor:
    command: emacs -nw +{line_number} {filename}
    console: true
    # A few other examples:
    #
    # vscode:
    # command: code -g {filename}:{line_number}
    # console: false
    #
    # pycharm:
    # command: charm --line {line_number} {filename}
    # console: false
    #
    # emacs/emacsclient:
    # command: emacs +{line_number} {filename}
    # console: false
